---
title: "Kashyap_HW2"
author: "Madhuri"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_floating: true
---

## Hoemwork 2

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#packages
library(tidymodels)
library(tidyverse)

#data
df <- read.csv("abalone.data")

#renaming column names
colnames(df) <- c('sex','length','diameter','ht','whole_wt','shucked_wt','viscera_wt',
                  'shell_wt','rings')
```


### Question 1

```{r}
#creating age = no. of rings + 1.5
df$age <- df$rings + 1.5
head(df)
mean(df$age)

#distribution of age
df %>% 
  ggplot(aes(x=age)) +
  geom_histogram() +
  theme_classic()
```

The age abalone shells is slightly positively skewed, implying that most of the abalones are younger in age (at the lower end), with a long tail to the right. Most abalones are 11 years old.


### Question 2

```{r}
set.seed(1995)

#splitting data
df_split <- initial_split(df, prop = 0.80, strata = age)
abalone_train <- training(df_split)
abalone_test <- testing(df_split)
```


### Question 3

```{r}
#creating recipe using training data
simple_abalone_recipe <- recipe(age ~ sex + length + diameter + ht + whole_wt + 
                                  shucked_wt + viscera_wt + shell_wt, 
                                data = abalone_train)
simple_abalone_recipe


#dummy coding categorical predictors
abalone_recipe <- simple_abalone_recipe %>% 
  step_dummy(all_nominal_predictors()) %>% 
  step_interact(terms = ~ sex_M:shucked_wt) %>% 
  step_interact(terms = ~ length:diameter) %>% 
  step_interact(terms = ~ shucked_wt:shell_wt) %>% 
  step_center(all_numeric_predictors()) %>% 
  step_scale(all_numeric_predictors())
abalone_recipe
```


### Question 4

```{r}
#creating and storing linear regression object
lm_model <- linear_reg() %>% 
  set_engine("lm")
```


### Question 5

```{r}
#empty workflow
lm_wflow <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(abalone_recipe)

summary(lm_wflow)
```


### Question 6

```{r}
#fitting to model and recipe
lm_fit <- fit(lm_wflow, abalone_train)
lm_fit %>% 
  extract_fit_parsnip() %>% 
  tidy()
```


### Question 7

```{r}
#training RMSE
abalone_train_res <- predict(lm_fit, new_data = abalone_train %>% select(-age))
abalone_train_res %>% 
  head()

#attaching column of actual observed age
abalone_train_res <- bind_cols(abalone_train_res, abalone_train %>% select(age))
abalone_train_res %>% 
  head()

#plotting predicted vs. observed
abalone_train_res %>% 
  ggplot(aes(x=.pred, y=jitter(age))) +
  geom_point(alpha = 0.2) +
  geom_abline(lty=2) +
  theme_classic() +
  coord_obs_pred()
```

